# Generated by Django 6.0.1 on 2026-03-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='num_predict',
            field=models.IntegerField(default=500, max_length=1000),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='temperature',
            field=models.FloatField(default=0.7, max_length=10),
        ),
    ]
