# Generated by Django 6.0.1 on 2026-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aiModel', models.CharField(max_length=100)),
                ('prompt', models.CharField(max_length=256)),
            ],
        ),
    ]
