# Generated by Django 6.0.1 on 2026-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisettings',
            name='prompt',
        ),
        migrations.AddField(
            model_name='aisettings',
            name='num_predict',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
